# Generated by Django 3.0.5 on 2020-11-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201103_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='views',
        ),
    ]
