# Generated by Django 3.0.5 on 2020-11-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
