# Generated by Django 3.0.5 on 2020-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201112_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
