# Generated by Django 3.0.5 on 2020-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200914_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
