# Generated by Django 3.0.5 on 2020-11-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201103_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
