# Generated by Django 3.0.5 on 2020-08-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200817_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text=('se establece en verdadero cuando el usuario ha verificado su dirección de correo electrónico',), verbose_name='verified'),
        ),
    ]
