# Generated by Django 3.0.7 on 2020-11-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models.project


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iteractions', '0002_auto_20201104_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.SlugField(max_length=255, unique=True, verbose_name=posts.models.project.Project)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
