# Generated by Django 3.0.5 on 2020-11-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteractions', '0002_auto_20201103_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
