# Generated by Django 3.0.7 on 2020-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteractions', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
