# Generated by Django 3.0.7 on 2020-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteractions', '0005_remove_likes_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
