# Generated by Django 3.0.7 on 2020-11-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteractions', '0006_likes_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='is_like',
        ),
    ]
